#include <pokemon.h>
#include <standardIO.h>

void iChooseYou(int num) {
    int bulbasaur = 0x008000;
    if(num == 0){
        printcFrom("                                           / \n", -1, -1, bulbasaur);
        printcFrom("                        _,.------....___,.' ',.-. \n", -1, -1, bulbasaur);
        printcFrom("                     ,-'          _,.--\"        |  \n", -1, -1, bulbasaur);
        printcFrom("                   ,'         _.-'              . \n", -1, -1, bulbasaur);
        printcFrom("                  /   ,     ,'                   ` \n", -1, -1, bulbasaur);
        printcFrom("                 .   /     /                     ``. \n", -1, -1, bulbasaur);
        printcFrom("                 |  |     .                       \\.\\ \n", -1, -1, bulbasaur);
        printcFrom("       ____      |___._.  |       __               \\ `. \n", -1, -1, bulbasaur);
        printcFrom("     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\ \n", -1, -1, bulbasaur);
        printcFrom("    .  ,            __               `              |   . \n", -1, -1, bulbasaur);
        printcFrom("     `,'         ,-\"'  .               \\             |    L \n", -1, -1, bulbasaur);
        printcFrom("      ,'          '    _.'                -._          /    | \n", -1, -1, bulbasaur);
        printcFrom("     ,`-.    ,\".   `--'                      >.      ,'     | \n", -1, -1, bulbasaur);
        printcFrom("    . .'\'   `-'       __    ,  ,-.         /  `.__.-      ,' \n", -1, -1, bulbasaur);
        printcFrom("    ||:, .           ,'  ;  /  / \\ `        `.    .      .'/ \n", -1, -1, bulbasaur);
        printcFrom("    j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , / \n", -1, -1, bulbasaur);
        printcFrom("   / L:_  |                 .  \"' :_;                `.'.' \n", -1, -1, bulbasaur);
        printcFrom("   .    \"\"'                  \"\"\"\"\"'                    V \n", -1, -1, bulbasaur);
        printcFrom("     `.                                 .    `.   _,..  ` \n", -1, -1, bulbasaur);
        printcFrom("       `,_   .    .                _,-'/    .. `,'   __  ` \n", -1, -1, bulbasaur);
        printcFrom("        ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  . \n", -1, -1, bulbasaur);
        printcFrom("       /   `. \"`-.--\"'         _,' ,'     `---' |    `./  | \n", -1, -1, bulbasaur);
        printcFrom("      .   _  `\"\"'--.._____..--\"   ,             '         | \n", -1, -1, bulbasaur);
        printcFrom("      | .\" `. `-.                /-.           /          , \n", -1, -1, bulbasaur);
        printcFrom("      | `._.'    `,_            ;  /         ,'          . \n", -1, -1, bulbasaur);
        printcFrom("     .'          /| `-.        . ,'         ,           , \n", -1, -1, bulbasaur);
        printcFrom("     '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.' \n", -1, -1, bulbasaur);
        printcFrom("     `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--'  \n\n", -1, -1, bulbasaur);

    }

    int butterfree = 0xC8A2C8;
    if(num == 1){
        printcFrom("           ,-.                                            ___.._ \n", -1, -1, butterfree);
        printcFrom("     _     `. `.                                    _,-\"\"\"      ',._ \n", -1, -1, butterfree);
        printcFrom("    `.`.      `.\\                                _,'         _..-'  `. \n", -1, -1, butterfree);
        printcFrom("      `._\\       `.                            ,'         _,'_,.-'-.  \\ \n", -1, -1, butterfree);
        printcFrom("          `.       `.                        ,'        ,-',-\"       \\  . \n", -1, -1, butterfree);
        printcFrom("            `.       \\                      /  _,----\"',-'           L  L \n", -1, -1, butterfree);
        printcFrom("              `.      \\                   ,' _.--\"-.  [              |  | \n", -1, -1, butterfree);
        printcFrom("                `.     .                 / ,'       | |     _..---../   | \n", -1, -1, butterfree);
        printcFrom("                  .     L               / /         | j ,.-'        `   | \n", -1, -1, butterfree);
        printcFrom("                   \\    .              ' /          j ,'             |  | \n", -1, -1, butterfree);
        printcFrom("                    \\    .            ' /          ' /               |  | \n", -1, -1, butterfree);
        printcFrom("                     \\   l           / /          /,'                j  ' \n", -1, -1, butterfree);
        printcFrom("                      L__L._        / /          +'      __,........'  j \n", -1, -1, butterfree);
        printcFrom("                    ,'   '  \"`.    / /         .' _,.--'\"           \\  | \n", -1, -1, butterfree);
        printcFrom("                   /,""-.      `. ' '        _/.-'                  | F \n", -1, -1, butterfree);
        printcFrom("                  /|   / l       . /       ,'                       | | \n", -1, -1, butterfree);
        printcFrom("                 | |  /  |       ]'      ,'                         | | \n", -1, -1, butterfree);
        printcFrom("                ,._\\\"'   |       |     ,'-'\"\"\"\"\"\"\"\"\"\"\"\"\"'----.._    / | \n", -1, -1, butterfree);
        printcFrom("                |  \\`.._,'       F  _,'                         `--'  | \n", -1, -1, butterfree);
        printcFrom("                `..'           _/ ,:_____                         L   | \n", -1, -1, butterfree);
        printcFrom("                  `..          .-'       `'--.._                   | j \n", -1, -1, butterfree);
        printcFrom("                _,. /,---.       \\              `--..              | | \n", -1, -1, butterfree);
        printcFrom("               F  <j-.'   `       ._                 `\"-._        j  ' \n", -1, -1, butterfree);
        printcFrom("               |  <|`,.    |       `L._                   `..   _, ,' \n", -1, -1, butterfree);
        printcFrom("               `..<|`.___,'        |.  `-.                   Y\"' _. \n", -1, -1, butterfree);
        printcFrom("                  `L               | `.   `-.._____________,',.-' \n", -1, -1, butterfree);
        printcFrom("                    `.            .Y   \\      `\"\".\"\"\"\"\".  .\"' \n", -1, -1, butterfree);
        printcFrom("                      `.        ,' |\\   `.        `+-._ \\  | \n", -1, -1, butterfree);
        printcFrom("                        `,--. -'   | .    `.       `   `.| | \n", -1, -1, butterfree);
        printcFrom("                        /    //    |  \\    ``-..___/     | | \n", -1, -1, butterfree);
        printcFrom("                       j    .l     |   .    F   \\   `   F  | \n", -1, -1, butterfree);
        printcFrom("                       |    ||     |    `   `    .   ` ,  / \n", -1, -1, butterfree);
        printcFrom("                       |    ||    F      `-.|     . _,' _' \n", -1, -1, butterfree);
        printcFrom("                       |   / |    |       `._`-----'  ,' \n", -1, -1, butterfree);
        printcFrom("                       |  /  |   /           `-------' \n", -1, -1, butterfree);
        printcFrom("                       l /   \\_,' \n", -1, -1, butterfree);
        printcFrom("                        \" \n\n", -1, -1, butterfree);
    }

    int charmander = 0xFF8000;
    if(num == 2){
        printcFrom("                 _.--""`-..\n", -1, -1, charmander);
        printcFrom("               ,'          `.\n", -1, -1, charmander);
        printcFrom("             ,'          __  `.\n", -1, -1, charmander);
        printcFrom("            /|          \" __   \\ \n", -1, -1, charmander);
        printcFrom("           , |           / |.   . \n", -1, -1, charmander);
        printcFrom("           |,'          !_.'|   | \n", -1, -1, charmander);
        printcFrom("         ,'             '   |   | \n", -1, -1, charmander);
        printcFrom("        /              |`--'|   | \n", -1, -1, charmander);
        printcFrom("       |                `---'   | \n", -1, -1, charmander);
        printcFrom("        .   ,                   |                       ,\". \n", -1, -1, charmander);
        printcFrom("         ._     '           _'  |                    , ' \\ ` \n", -1, -1, charmander);
        printcFrom("     `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,| \n", -1, -1, charmander);
        printcFrom("     |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\ \n", -1, -1, charmander);
        printcFrom("   -:..     `. `-..--_.,.<       `\"      / `.        `-/ |   . \n", -1, -1, charmander);
        printcFrom("     `,         \"\"\"\"'     `.              ,'         |   |  ',, \n", -1, -1, charmander);
        printcFrom("       `.      '            '            /          '    |'. |/ \n", -1, -1, charmander);
        printcFrom("         `.   |              \\       _,-'           |       '' \n", -1, -1, charmander);
        printcFrom("           `._'               \\   '\"\\                .      | \n", -1, -1, charmander);
        printcFrom("              |                '     \\                `._  ,' \n", -1, -1, charmander);
        printcFrom("              |                 '     \\                 .'| \n", -1, -1, charmander);
        printcFrom("              |                 .      \\                | | \n", -1, -1, charmander);
        printcFrom("              |                 |       L              ,' | \n", -1, -1, charmander);
        printcFrom("              `                 |       |             /   ' \n", -1, -1, charmander);
        printcFrom("               \\                |       |           ,'   / \n", -1, -1, charmander);
        printcFrom("             ,' \\               |  _.._ ,-..___,..-'    ,' \n", -1, -1, charmander);
        printcFrom("            /     .             .      `!             ,j' \n", -1, -1, charmander);
        printcFrom("           /       `.          /        .           .'/ \n", -1, -1, charmander);
        printcFrom("          .          `.       /         |        _.'.' \n", -1, -1, charmander);
        printcFrom("           `.          7`'---'          |------\"'_.' \n", -1, -1, charmander);
        printcFrom("          _,.`,_     _'                ,''-----\"' \n", -1, -1, charmander);
        printcFrom("      _,-_    '       `.     .'      ,\\ \n", -1, -1, charmander);
        printcFrom("      -\" /`.         _,'     | _  _  _.| \n", -1, -1, charmander);
        printcFrom("       \"\"--'---\"\"\"\"\"'        `' '! |! / \n", -1, -1, charmander);
        printcFrom("                              `\" \" -'\" \n\n", -1, -1, charmander);
    }

    int marowak = 0xFFa420;
    if(num == 3) {
        printcFrom("         ,.                           __     ,\"`. \n", -1, -1, marowak);
        printcFrom("        / |                      _.-\"'  `\"--'   | \n", -1, -1, marowak);
        printcFrom("       /  |              .\"--..,'               | \n", -1, -1, marowak);
        printcFrom("      j   |              `                      | \n", -1, -1, marowak);
        printcFrom("      '    `-.            `.                    | \n", -1, -1, marowak);
        printcFrom("     .       .'            '                    | \n", -1, -1, marowak);
        printcFrom("     |    ,-\"               .                   ' \n", -1, -1, marowak);
        printcFrom("     |     \\                |                    ,\"\"`. \n", -1, -1, marowak);
        printcFrom("     |      \\               |                   ||    ` \n", -1, -1, marowak);
        printcFrom("     |       \\             j     `-.           .||     `. \n", -1, -1, marowak);
        printcFrom("     |        \\            |       |`.         |||      | \n", -1, -1, marowak);
        printcFrom("     |         \\         __|       |  |`.      |'|\\   .' \n", -1, -1, marowak);
        printcFrom("     |          `.  _.-\"'   `-.._  `._'  `.    | | `-\" \n", -1, -1, marowak);
        printcFrom("     |          _,+\"             `.   `\\\"\"--\\     | \n", -1, -1, marowak);
        printcFrom("     '        .'                   `.            | \n", -1, -1, marowak);
        printcFrom("     '      ,'                      |`.       .  ' \n", -1, -1, marowak);
        printcFrom("      \\   .'                        `. `.     , / \n", -1, -1, marowak);
        printcFrom("       \\,'             _,.-+""'.      `  `.   .' \n", -1, -1, marowak);
        printcFrom("       /            .-'     `-. '      `.  `\"' \n", -1, -1, marowak);
        printcFrom("     ,'           ,'\\          `.`.      ` \n", -1, -1, marowak);
        printcFrom("    '            /.  `.         ,\\ \\      `._ \n", -1, -1, marowak);
        printcFrom("   .            /  \\   `._    .'  \\ .        `\". \n", -1, -1, marowak);
        printcFrom("   |           /._  `-._  `,-'    ,' `.         \\ \n", -1, -1, marowak);
        printcFrom("   |          /   `\"-+---\"'      |    |         ,-.._ \n", -1, -1, marowak);
        printcFrom("   |..____,.-'       |`.         '   ,'         |    `\"-._        __ \n", -1, -1, marowak);
        printcFrom("   `---'\"            |  \\         `.'  `-.._   ,|      `._`\"-._.\"'  `. \n", -1, -1, marowak);
        printcFrom("                     |`._`.        |        `.  `-._      \"-          . \n", -1, -1, marowak);
        printcFrom("                      `.,' `.___..'           `\"    `._                | \n", -1, -1, marowak);
        printcFrom("                                                       `.              | \n", -1, -1, marowak);
        printcFrom("                                                         `._         .' \n", -1, -1, marowak);
        printcFrom("                                                            `        | \n", -1, -1, marowak);
        printcFrom("                                                             .       | \n", -1, -1, marowak);
        printcFrom("                                                              \\      | \n", -1, -1, marowak);
        printcFrom("                                                               `..,.' \n\n", -1, -1, marowak);
    }

    int slowpoke = 0xFE4164;
    if(num == 4) {
        printcFrom("                                     _.---\"'\"\"\"\"\"'`--.._ \n", -1, -1, slowpoke);
        printcFrom("                                _,.-'                   `-._ \n", -1, -1, slowpoke);
        printcFrom("                            _,.\"                            -. \n", -1, -1, slowpoke);
        printcFrom("                        .-""   ___...---------.._             `. \n", -1, -1, slowpoke);
        printcFrom("                        `---'""                  `-.            `. \n", -1, -1, slowpoke);
        printcFrom("                                                    `.            \\ \n", -1, -1, slowpoke);
        printcFrom("                                                      `.           \\ \n", -1, -1, slowpoke);
        printcFrom("                                                        \\           \\ \n", -1, -1, slowpoke);
        printcFrom("                                                         .           \\ \n", -1, -1, slowpoke);
        printcFrom("                                                         |            . \n", -1, -1, slowpoke);
        printcFrom("                                                         |            | \n", -1, -1, slowpoke);
        printcFrom("                                   _________             |            | \n", -1, -1, slowpoke);
        printcFrom("                             _,.-'\"         `\"'-.._      :            | \n", -1, -1, slowpoke);
        printcFrom("                         _,-'                      `-._.'             | \n", -1, -1, slowpoke);
        printcFrom("                      _.'                              `.             ' \n", -1, -1, slowpoke);
        printcFrom("           _.-.    _,+......__                           `.          . \n", -1, -1, slowpoke);
        printcFrom("         .'    `-\"'           `\"-.,-\"\"--._                 \\        / \n", -1, -1, slowpoke);
        printcFrom("        /    ,'                  |    __  \\                 \\      / \n", -1, -1, slowpoke);
        printcFrom("       `   ..                       +\"  )  \\                 \\    / \n", -1, -1, slowpoke);
        printcFrom("        `.'  \\          ,-\"`-..    |       |                  \\  / \n", -1, -1, slowpoke);
        printcFrom("         / \" |        .'       \\   '.    _.'                   .' \n", -1, -1, slowpoke);
        printcFrom("        |,..\"--\"\"\"--..|    \"    |    `\"\"`.                     | \n", -1, -1, slowpoke);
        printcFrom("      ,\"               `-._     |        |                     | \n", -1, -1, slowpoke);
        printcFrom("    .'                     `-._+         |                     | \n", -1, -1, slowpoke);
        printcFrom("   /                           `.                        /     | \n", -1, -1, slowpoke);
        printcFrom("   |    `     '                  |                      /      | \n", -1, -1, slowpoke);
        printcFrom("   `-.....--.__                  |              |      /       | \n", -1, -1, slowpoke);
        printcFrom("      `./ \"| / `-.........--.-   '              |    ,'        ' \n", -1, -1, slowpoke);
        printcFrom("        /| ||        `.'  ,'   .'               |_,-+         / \n", -1, -1, slowpoke);
        printcFrom("       / ' '.`.        _,'   ,'     `.          |   '   _,.. / \n", -1, -1, slowpoke);
        printcFrom("      /   `.  `\"'\"'\"\"'\"   _,^--------\"`.        |    `.'_  _/ \n", -1, -1, slowpoke);
        printcFrom("     /... _.`:.________,.'              `._,.-..|        \"' \n", -1, -1, slowpoke);
        printcFrom("    `.__.'                                 `._  / \n", -1, -1, slowpoke);
        printcFrom("                                              \"'  \n\n", -1, -1, slowpoke);
    }

    int eevee = 0x804000;
    if(num == 5) {
        printcFrom("                                         | \n", -1, -1, eevee);
        printcFrom("                                        /| \n", -1, -1, eevee);
        printcFrom("                                      ,' | \n", -1, -1, eevee);
        printcFrom("                                     .   | \n", -1, -1, eevee);
        printcFrom("                                       | | \n", -1, -1, eevee);
        printcFrom("                                    ' '| | \n", -1, -1, eevee);
        printcFrom("                                   / / | | \n", -1, -1, eevee);
        printcFrom("          _,.-""--._              / /  | | \n", -1, -1, eevee);
        printcFrom("        ,'          `.           j '   ' ' \n", -1, -1, eevee);
        printcFrom("       ,'              `.         ||   / ,                         ___..--, \n", -1, -1, eevee);
        printcFrom("      /                  \\        ' `.'`.-.,-\".  .       _..---\"\"'' __, ,' \n", -1, -1, eevee);
        printcFrom("     /                    \\        \\` .\"`      `\"'\\   ,'\"_..--''\"\"\"'.'.' \n", -1, -1, eevee);
        printcFrom("    .                      .      .'-'             \\,' ,'         ,',' \n", -1, -1, eevee);
        printcFrom("    |                      |      ,`               ' .`         .' / \n", -1, -1, eevee);
        printcFrom("    |                      |     /          ,\"`.  ' `-. _____.-' .' \n", -1, -1, eevee);
        printcFrom("    '                      |..---.|,\".      | | .  .-'\"\"   __.,-' \n", -1, -1, eevee);
        printcFrom("    .                   ,'       ||,|      |.' |    |\"\"`'\" \n", -1, -1, eevee);
        printcFrom("     `-._   `._.._____  |        || |      `._,'    | \n", -1, -1, eevee);
        printcFrom("         `.   .       `\".     ,'\"| \"  `'           ,+. \n", -1, -1, eevee);
        printcFrom("           \\  '         |    '   |   .....        .'  `. \n", -1, -1, eevee);
        printcFrom("            .'          '     7  \".              ,'     \\ \n", -1, -1, eevee);
        printcFrom("                      ,'      |    `..        _,'      F \n", -1, -1, eevee);
        printcFrom("                     .        |,      `'----''         | \n", -1, -1, eevee);
        printcFrom("                     |      ,\"j  /                   | ' \n", -1, -1, eevee);
        printcFrom("                     `     |  | .                 | `,' \n", -1, -1, eevee);
        printcFrom("                      .    |  `.|                 |/ \n", -1, -1, eevee);
        printcFrom("                       `-..'   ,'                .' \n", -1, -1, eevee);
        printcFrom("                              | \\             ,'' \n", -1, -1, eevee);
        printcFrom("                              |  `,'.      _,' / \n", -1, -1, eevee);
        printcFrom("                              |    | ^.  .'   / \n", -1, -1, eevee);
        printcFrom("                               `-'.' j` V    / \n", -1, -1, eevee);
        printcFrom("                                     |      / \n", -1, -1, eevee);
        printcFrom("                                     |     / \n", -1, -1, eevee);
        printcFrom("                                     |   ,' \n", -1, -1, eevee);
        printcFrom("                                      `""  \n\n", -1, -1, eevee);
    }

    int gastly = 0x78288C;
    if(num == 6) {
        printcFrom("                             _ \n", -1, -1, gastly);
        printcFrom("                          .\"' `..._ \n", -1, -1, gastly);
        printcFrom("                         '         `. \n", -1, -1, gastly);
        printcFrom("                        .'      ___..' \n", -1, -1, gastly);
        printcFrom("                  _   .\"       '   .__,-.,\"\", ,----. \n", -1, -1, gastly);
        printcFrom("       ,.-\"\"''-..\" :  :        `--'        ' :      : \n", -1, -1, gastly);
        printcFrom("     .'            :_,'                    `._`\"--. ; \n", -1, -1, gastly);
        printcFrom("     :              _,.--'\"'\"\"`--._           `.  `\" \n", -1, -1, gastly);
        printcFrom("    j             ,'               `-.      ,._.'  ,\"\". \n", -1, -1, gastly);
        printcFrom("    :           ,'                   ,-.   .   __  `..' \n", -1, -1, gastly);
        printcFrom("     `--.    .'.'                   ,'   `. :_,\"  `. \n", -1, -1, gastly);
        printcFrom("   ,.   ;   .   \\                 ,'      |         `. \n", -1, -1, gastly);
        printcFrom("  ' :  :    |    `.             ,'        |\\         `.  _ \n", -1, -1, gastly);
        printcFrom("   `.   ._  |      \\         _.'          | .      ___ `\" : \n", -1, -1, gastly);
        printcFrom("          : '     . \\      ,'  .          ' |     :   `...' \n", -1, -1, gastly);
        printcFrom("         ,'  \\       `.   .             ,'  |     '  __ \n", -1, -1, gastly);
        printcFrom("        .    `.       |    \\          .'    '    .  (  `. \n", -1, -1, gastly);
        printcFrom("       .'      \\`.___,'      `-.____.-'     '     :   `-.' \n", -1, -1, gastly);
        printcFrom("        .   ,\". \\ ..___              _     /      :    . \n", -1, -1, gastly);
        printcFrom("        :   . :  \\|/\\  `\"'--------+\"|,'  ,'       `-..' : \n", -1, -1, gastly);
        printcFrom("         `-\" .'   `: `\"-.._______,.\\|  .'               ' \n", -1, -1, gastly);
        printcFrom("             `--. _ `._             _,'        ,\"\"-.__,' \n", -1, -1, gastly);
        printcFrom("                 \" :   `\"--.....--\"'     __   . \n", -1, -1, gastly);
        printcFrom("                 ,-'                 ,.-\"  `-' \n", -1, -1, gastly);
        printcFrom("                :   ,..             .    ,\"\". \n", -1, -1, gastly);
        printcFrom("               .'   .  :   __..._   `\"-. :   : \n", -1, -1, gastly);
        printcFrom("               `.._  : ' ,'      `\"--..' `--\" \n", -1, -1, gastly);
        printcFrom("                   `-' `\" \n\n", -1, -1, gastly);
    }

    int geodude = 0x9C9C9C;
    if(num == 7) {
        printcFrom("                                              _,.---. \n", -1, -1, geodude);
        printcFrom("                                          _,-'       `. \n", -1, -1, geodude);
        printcFrom("                                        _,'  ,          \\ \n", -1, -1, geodude);
        printcFrom("                                      ,'  _,'   .        `. \n", -1, -1, geodude);
        printcFrom("                                     /  ,'     ,'          `. \n", -1, -1, geodude);
        printcFrom("            __                       .,'    _,'              `. \n", -1, -1, geodude);
        printcFrom("       _,..'  `-....___              :    ,'     '             \\ \n", -1, -1, geodude);
        printcFrom("     ,'   /            :             /`.,'      /               ` \n", -1, -1, geodude);
        printcFrom("    /    /  ._         |         __..|  `.    .'       ,         `. \n", -1, -1, geodude);
        printcFrom("    |   |   ,'\"--._    |      ,-'    `-._`.,-'       ,:            . \n", -1, -1, geodude);
        printcFrom("   .'\\   \\     _,'.    `'___.'           `\"`.     _,' /            | \n", -1, -1, geodude);
        printcFrom("   |  \\   \\---'       ,\"'  .-\"\"'\"----.       `.  '  ,'             | \n", -1, -1, geodude);
        printcFrom("    `. `-.'          /    /                    `-..^._             ' \n", -1, -1, geodude);
        printcFrom("      |._|    _.    /    /                            `._           . \n", -1, -1, geodude);
        printcFrom("      `...:--'--+..'   ,'                              /            | \n", -1, -1, geodude);
        printcFrom("          '._  `|   ,-'       _..._                   j     \\       | \n", -1, -1, geodude);
        printcFrom("            |` |   /       ,-'     `-.__              |      L      | \n", -1, -1, geodude);
        printcFrom("            |  |  /      ,'                           |      |      | \n", -1, -1, geodude);
        printcFrom("            |_,'        /         _,-                  .     |      | \n", -1, -1, geodude);
        printcFrom("           ,'  ,   |  ,'        ,|            ,..._     \\    |      ' \n", -1, -1, geodude);
        printcFrom("          ,     \\ j  '       _.\" |           /     `-.__'    '    ,' \n", -1, -1, geodude);
        printcFrom("           +._   '|       ,'|    |          /        ,'    .'    / \n", -1, -1, geodude);
        printcFrom("           |  `._  `-' .:|  |    '.       -'        '           j \n", -1, -1, geodude);
        printcFrom("           '    |`    ' |'  |     |                             | \n", -1, -1, geodude);
        printcFrom("            `.  |       |--'     _|        .                    | \n", -1, -1, geodude);
        printcFrom("              \\ |       '----'\"\"\"           \\      __,....-+----' \n", -1, -1, geodude);
        printcFrom("               | '                            `---""      .' \n", -1, -1, geodude);
        printcFrom("                `. `.                                     , \n", -1, -1, geodude);
        printcFrom("                  `\" \\_...-\"\"\"'--..         _+          ,' \n", -1, -1, geodude);
        printcFrom("                       '            -.'  `-'  `.  .\"-..' \n", -1, -1, geodude);
        printcFrom("                        `-..._            _____,.' \n", -1, -1, geodude);
        printcFrom("                              `--.....,-\"' \n\n", -1, -1, geodude);
    }

    int growlithe = 0xF44611;
    if(num == 8){
        printcFrom("                    _, \n", -1, -1, growlithe);
        printcFrom("                  .',_.., \n", -1, -1, growlithe);
        printcFrom("                ,'     /,-- \n", -1, -1, growlithe);
        printcFrom("              .'       ,./.__ \n", -1, -1, growlithe);
        printcFrom("              |_,.----/,,'`.  _ \n", -1, -1, growlithe);
        printcFrom("             .'__     //    `...> \n", -1, -1, growlithe);
        printcFrom("        ____//|) |    `      /.' \n", -1, -1, growlithe);
        printcFrom("       (/    `-.-'.._     _,|                 ,.-------.._ \n", -1, -1, growlithe);
        printcFrom("       .             `.  '   \\               /            `-._ \n", -1, -1, growlithe);
        printcFrom("       `..---._       |       `.            j                 `. \n", -1, -1, growlithe);
        printcFrom("         >-,-\"`\"\"'    |        |`\"+-..__    |              -. `-. \n", -1, -1, growlithe);
        printcFrom("        ( /|         /____     |  |  |  \\\"\"|+-.._     ___    `.  `. \n", -1, -1, growlithe);
        printcFrom("         \" `-..._     \"--,_    |  |  `   | |   | `.-.\"   \"-._  |  -` \n", -1, -1, growlithe);
        printcFrom("              ,'        '_>_   j ,'  '. ,` |,  |   `. `.-v.' `-+..._`. \n", -1, -1, growlithe);
        printcFrom("             '.         >       '     | |  ' \\ L     ..`.  '        `._ \n", -1, -1, growlithe);
        printcFrom("              '.       /              '|`     \\|      '^,         ..,{ `. \n", -1, -1, growlithe);
        printcFrom("             / /      /                '       v          |__    ___,'\"\" \n", -1, -1, growlithe);
        printcFrom("           ,'  >---+-+.        |   __,..--\"`-._          /.-'`\"----' \n", -1, -1, growlithe);
        printcFrom("          /`.       `. '.      |-\"'            `\"--....-'._ \n", -1, -1, growlithe);
        printcFrom("        .'___'        `._`,    j             ___,-','      `-..._ \n", -1, -1, growlithe);
        printcFrom("   _ _.'    '/.-          '  ,'       __..<""__,.-'              `. \n", -1, -1, growlithe);
        printcFrom("   `.)         |'---\"\"`.+-.--'-------\"\"-...__  ,-'/ .\"\\          _  | \n", -1, -1, growlithe);
        printcFrom("   ,\"\\ ,--.  _,-          ` `'                `'\"\"\"'`\"'\"\"\"`--._  . `/ \n", -1, -1, growlithe);
        printcFrom("   `-`.___.'                                                  `\"-\"' \n\n", -1, -1, growlithe);
    }

    int jigglypuff = 0xFFCBDB;
    if(num == 9) {
        printcFrom("       ,..__ \n", -1, -1, jigglypuff);
        printcFrom("       |  _  `--._                                  _.--\"\"\"`. \n", -1, -1, jigglypuff);
        printcFrom("       |   |._    `-.        __________         _.-'    ,|' | \n", -1, -1, jigglypuff);
        printcFrom("       |   |  `.     `-..--""_.        `""-..,-'      ,' |  | \n", -1, -1, jigglypuff);
        printcFrom("       L   |    `.        ,-'                      _,'   |  | \n", -1, -1, jigglypuff);
        printcFrom("        .  |     ,'     ,'            .           '.     |  | \n", -1, -1, jigglypuff);
        printcFrom("        |  |   ,'      /               \\            `.   |  | \n", -1, -1, jigglypuff);
        printcFrom("        |  . ,'      ,'                |              \\ /  j \n", -1, -1, jigglypuff);
        printcFrom("        `   \"       ,                  '               `   / \n", -1, -1, jigglypuff);
        printcFrom("         `,         |                ,'                  '+ \n", -1, -1, jigglypuff);
        printcFrom("         /          |             _,'                     ` \n", -1, -1, jigglypuff);
        printcFrom("        /     .-\"\"\"'L          ,-' \\  ,-'\"\"\"\"`-.           ` \n", -1, -1, jigglypuff);
        printcFrom("       j    ,' ,.+--.\\        '    ',' ,.,-\"--._`.          \\ \n", -1, -1, jigglypuff);
        printcFrom("       |   / .'  L    `.        _.'/ .'  |      \\ \\          . \n", -1, -1, jigglypuff);
        printcFrom("      j   | | `--'     |`+-----'  . j`._,'       L |         | \n", -1, -1, jigglypuff);
        printcFrom("      |   L .          | |        | |            | |         | \n", -1, -1, jigglypuff);
        printcFrom("      |   `\\ \\        / j         | |            | |         | \n", -1, -1, jigglypuff);
        printcFrom("      |     \\ `-.._,.- /           . `         .'  '         | \n", -1, -1, jigglypuff);
        printcFrom("      l      `-..__,.-'             `.`-.....-' _.'          ' \n", -1, -1, jigglypuff);
        printcFrom("      '                               `-.....--'            j \n", -1, -1, jigglypuff);
        printcFrom("       .                  -.....                            | \n", -1, -1, jigglypuff);
        printcFrom("        L                  `---'                            ' \n", -1, -1, jigglypuff);
        printcFrom("         \\                                                 / \n", -1, -1, jigglypuff);
        printcFrom("          ` \\                                        ,   ,' \n", -1, -1, jigglypuff);
        printcFrom("           `.`.    |                        /      ,'   . \n", -1, -1, jigglypuff);
        printcFrom("             . `._,                        |     ,'   .' \n", -1, -1, jigglypuff);
        printcFrom("              `.                           `._.-'  ,-' \n", -1, -1, jigglypuff);
        printcFrom("         _,-\"\"\"\"`-,                             _,'\"-.._ \n", -1, -1, jigglypuff);
        printcFrom("       ,'          `-.._                     ,-'        `. \n", -1, -1, jigglypuff);
        printcFrom("      /             _,' `\"-..___     _,..--\"`.            `. \n", -1, -1, jigglypuff);
        printcFrom("     |         _,.-'            `\"\"\"'         `-._          \\ \n", -1, -1, jigglypuff);
        printcFrom("     `-....---'                                   `-.._      | \n", -1, -1, jigglypuff);
        printcFrom("                                                       `--...' \n\n", -1, -1, jigglypuff);
    }

    int meowth = 0xF9E4B7;
    if(num == 10) {
        printcFrom("                                          . \n", -1, -1, meowth);
        printcFrom("                           |              | \n", -1, -1, meowth);
        printcFrom("                           |             ,| \n", -1, -1, meowth);
        printcFrom("                  ,_       |\\            F'   ,.-""`. \n", -1, -1, meowth);
        printcFrom("                 /  `-._   |`           // ,-\"_,..  | \n", -1, -1, meowth);
        printcFrom("                |   ___ `. | \\ ,\"\"\"`-. /.-' ,'    ' |_....._ \n", -1, -1, meowth);
        printcFrom("                |  /   `-.`.  L......|j j_.'      ` |       `._ \n", -1, -1, meowth);
        printcFrom("                | |      _,'| |______|' | '-._     ||  ,.-.    `. \n", -1, -1, meowth);
        printcFrom("                 L|    ,'   | |      | j      `-.  || '    `.    \\ \n", -1, -1, meowth);
        printcFrom("  ___            | \\_,'     | |`\"----| |         `.||       |\\    \\ \n", -1, -1, meowth);
        printcFrom("   ""=+...__     `,'   ,.-.   |....._|   _....     Y \\      j_),..+=-- \n", -1, -1, meowth);
        printcFrom("       `\"-._\"._  .   ,' |  `   \\    /  ,' |   \\     \\ j,..-\"_..+-\"  L \n", -1, -1, meowth);
        printcFrom("            `-._-+. j   !   \\   `--'  .   !    \\  ,.-\" _..<._  |    | \n", -1, -1, meowth);
        printcFrom("                |-. |   |    L        |   !     |  .-/'      `.|-.,-| \n", -1, -1, meowth);
        printcFrom("                |__ '   '    |        '   |    /    /|   `, -. |   j \n", -1, -1, meowth);
        printcFrom("           _..--'\"__  `-.___,'          `.___,.'  __/_|_  /   / '   | \n", -1, -1, meowth);
        printcFrom("      _.-_..---\"\"_.-\\                            .,...__\"\"--./L/_   | \n", -1, -1, meowth);
        printcFrom("    -'""'     ,""  ,-`-.    .___.,...___,    _,.+\"      \"\"\"\"`-+-==++- \n", -1, -1, meowth);
        printcFrom("             / /  `.   )\"-.._`v \\|    V/  /-'    \\._,._.'\"-. /    / \n", -1, -1, meowth);
        printcFrom("             ` `.  )---.     `\"\"\\__  / .'        /    \\    Y\"._.' \n", -1, -1, meowth);
        printcFrom("              `\"'`\"     `-.     /|._\\\"\"_/         |  ,..   _ |  | \n", -1, -1, meowth);
        printcFrom("                           `\"\"\"' |  \"'           `. `-'  (_|,-.' \n", -1, -1, meowth);
        printcFrom("                                 \\               |`       .`- \n", -1, -1, meowth);
        printcFrom("                                  `.           . j`._    / \n", -1, -1, meowth);
        printcFrom("                                   |`.._     _.'|    `\"\"/ \n", -1, -1, meowth);
        printcFrom("                                   |    /\"\"'\"   |  .\". j \n", -1, -1, meowth);
        printcFrom("                                  .`.__j         \\ `.' | \n", -1, -1, meowth);
        printcFrom("                                  j    |          `._.' \n", -1, -1, meowth);
        printcFrom("                                 /     | \n", -1, -1, meowth);
        printcFrom("                                /,  ,  \\ \n", -1, -1, meowth);
        printcFrom("                                \\|  |   L \n", -1, -1, meowth);
        printcFrom("                                 `..|_..' \n\n", -1, -1, meowth);
    }

    int pidgey = 0xC3A98B;
    if(num == 11){
        printcFrom("                      ., \n", -1, -1, pidgey);
        printcFrom("               , _.-',' \n", -1, -1, pidgey);
        printcFrom("             \"\"|\"    `\"\"\"\"., \n", -1, -1, pidgey);
        printcFrom("            /'/       __.-'-\"/ \n", -1, -1, pidgey);
        printcFrom("           ','  _,--\"\"      '-._ \n", -1, -1, pidgey);
        printcFrom("       _...`...'.\"\"\"\"\"\".\\\"\"-----' \n", -1, -1, pidgey);
        printcFrom("    ,-'          `-.) /  `.  \\ \n", -1, -1, pidgey);
        printcFrom("   +---.\"-.    |     `.    .  \\ \n", -1, -1, pidgey);
        printcFrom("        \\  `.  |       \\   |   L \n", -1, -1, pidgey);
        printcFrom("         `v  ,-j        , .'   | \n", -1, -1, pidgey);
        printcFrom("        .'\\,' /        /,'      -._ \n", -1, -1, pidgey);
        printcFrom("       ,____.'        .            `-. \n", -1, -1, pidgey);
        printcFrom("           |         /                `-. \n", -1, -1, pidgey);
        printcFrom("          /          `.                  `-. \n", -1, -1, pidgey);
        printcFrom("         /             `. |                 `.                  _. \n", -1, -1, pidgey);
        printcFrom("        .                `|                 ,-.             _.-\" . \n", -1, -1, pidgey);
        printcFrom("       j                  |                 |  \\         _.'    / \n", -1, -1, pidgey);
        printcFrom("       .                  |               .'    \\     ,-'      / \n", -1, -1, pidgey);
        printcFrom("       |                  |            ,-.\\      \\  ,'      _.- \n", -1, -1, pidgey);
        printcFrom("       |                . '  `.       |   `      `v'  _,.-\"/ \n", -1, -1, pidgey);
        printcFrom("       ||    \\          |  ` |(`'-`.,.j         \\ `.-'----+---. \n", -1, -1, pidgey);
        printcFrom("       |'|   |L    \\  | |   `|   \'              L \\___      / \n", -1, -1, pidgey);
        printcFrom("       ' L   |`     L | |     `.                 | j   `\"\"\"-' \n", -1, -1, pidgey);
        printcFrom("          `-'||\\    | ||j       `.       ._    ` '. \n", -1, -1, pidgey);
        printcFrom("             `\\ '\"`^\"- '          `.       \\    |/| \n", -1, -1, pidgey);
        printcFrom("               `._                  `-.     \\   Y | \n", -1, -1, pidgey);
        printcFrom("       __,..-""`..`._                  `-._  `\\ `.| \n", -1, -1, pidgey);
        printcFrom("      +.....>+----.' \"\"----.........,--\"\"\" `--.'.' \n", -1, -1, pidgey);
        printcFrom("          ,' _\\  ,..--.-\"' __>---'  | \n", -1, -1, pidgey);
        printcFrom("         --\"\"  \"'  _.\" }<\"\"          `---\"\"`._ \n", -1, -1, pidgey);
        printcFrom("                  /...\"  L__.+--   _,......'..' \n", -1, -1, pidgey);
        printcFrom("                    /.-\"\"'/   \\ ,-' \n", -1, -1, pidgey);
        printcFrom("                        .' ,-\"\"' \n", -1, -1, pidgey);
        printcFrom("                       /.-' \n\n", -1, -1, pidgey);
    }

    int pikachu = 0xFFFF00;
    if(num == 12) {
        printcFrom("      quu..__ \n", -1, -1, pikachu);
        printcFrom("       $$$b  `---.__ \n", -1, -1, pikachu);
        printcFrom("        \"$$b        `--.                          ___.---uuudP \n", -1, -1, pikachu);
        printcFrom("         `$$b           `.__.------.__     __.---'      $$$$\"              . \n", -1, -1, pikachu);
        printcFrom("           \"$b          -'            `-.-'            $$$\"              .'| \n", -1, -1, pikachu);
        printcFrom("             \".                                       d$\"             _.'  | \n", -1, -1, pikachu);
        printcFrom("               `.   /                              ...\"             .'     | \n", -1, -1, pikachu);
        printcFrom("                 `./                           ..::-'            _.'       | \n", -1, -1, pikachu);
        printcFrom("                  /                         .:::-'            .-'         .' \n", -1, -1, pikachu);
        printcFrom("                 :                          ::''\\          _.'            | \n", -1, -1, pikachu);
        printcFrom("                .' .-.             .-.           `.      .'               | \n", -1, -1, pikachu);
        printcFrom("                : /'$$|           .@\"$\\           `.   .'              _.-' \n", -1, -1, pikachu);
        printcFrom("               .'|$u$$|          |$$,$$|           |  <            _.-' \n", -1, -1, pikachu);
        printcFrom("               | `:$$:'          :$$$$$:           `.  `.       .-' \n", -1, -1, pikachu);
        printcFrom("               :                  `\"--'             |    `-.     \\ \n", -1, -1, pikachu);
        printcFrom("              :##.       ==             .###.       `.      `.    `\\ \n", -1, -1, pikachu);
        printcFrom("              |##:                      :###:        |        >     > \n", -1, -1, pikachu);
        printcFrom("              |#'     `..'`..'          `###'        x:      /     / \n", -1, -1, pikachu);
        printcFrom("               \\                                   xXX|     /    ./ \n", -1, -1, pikachu);
        printcFrom("                \\                                xXXX'|    /   ./ \n", -1, -1, pikachu);
        printcFrom("                /`-.                                  `.  /   / \n", -1, -1, pikachu);
        printcFrom("               :    `-  ...........,                   | /  .' \n", -1, -1, pikachu);
        printcFrom("               |         ``:::::::'       .            |<    `. \n", -1, -1, pikachu);
        printcFrom("               |             ```          |           x| \\ `.:``. \n", -1, -1, pikachu);
        printcFrom("               |                         .'    /'   xXX|  `:`M`M':. \n", -1, -1, pikachu);
        printcFrom("              |    |                    ;    /:' xXXX'|  -'MMMMM:' \n", -1, -1, pikachu);
        printcFrom("               `.  .'                   :    /:'       |-'MMMM.-' \n", -1, -1, pikachu);
        printcFrom("                |  |                   .'   /'        .'MMM.-' \n", -1, -1, pikachu);
        printcFrom("                `'`'                   :  ,'          |MMM< \n", -1, -1, pikachu);
        printcFrom("                  |                     `'            |tbap\\ \n", -1, -1, pikachu);
        printcFrom("                   \\                                  :MM.-' \n", -1, -1, pikachu);
        printcFrom("                    \\                 |              .'' \n", -1, -1, pikachu);
        printcFrom("                     \\.               `.            / \n", -1, -1, pikachu);
        printcFrom("                      /     .:::::::.. :           / \n", -1, -1, pikachu);
        printcFrom("                     |     .:::::::::::`.         / \n", -1, -1, pikachu);
        printcFrom("                     |   .:::------------\\       / \n", -1, -1, pikachu);
        printcFrom("                    /   .''               >::'  / \n", -1, -1, pikachu);
        printcFrom("                    `',:                 :    .' \n", -1, -1, pikachu);
        printcFrom("                                         `:.:' \n\n", -1, -1, pikachu);
    }

    int poliwag = 0x3B83BD;
    if(num == 13) {
        printcFrom("        _..__                                    ___ \n", -1, -1, poliwag);
        printcFrom("       /     `._                          ,--\"\"\"\"   `\"-. \n", -1, -1, poliwag);
        printcFrom("      |         `.                    _.'\"\"/`.        |/`-. \n", -1, -1, poliwag);
        printcFrom("      |           `.                ,+ `..' | |       |'...+. \n", -1, -1, poliwag);
        printcFrom("      |     \\       \\              / /\\____,' '    __ `.`._,\". \n", -1, -1, poliwag);
        printcFrom("      |      ..      \\           ,'  \\      .' ,-\"'  `. `.._,'`. \n", -1, -1, poliwag);
        printcFrom("      |       .`.     \\         /     `-..-'  .  _.... |._      \\ \n", -1, -1, poliwag);
        printcFrom("      '        ' `     \\       /          ,-\"\"`.____...'  `.     \\ \n", -1, -1, poliwag);
        printcFrom("       `        `.`.    \\     '         ,'   _,--------.`.  `.    L \n", -1, -1, poliwag);
        printcFrom("        `         ` `.   \\   j         /  .,' ,\"_.....`.`.`   \\   | \n", -1, -1, poliwag);
        printcFrom("         `.        `. `.  \\  |        / ,'/ .','..... `.\\ \\|   .  | \n", -1, -1, poliwag);
        printcFrom("           `.        `. .  \\ |       j . / ..'.,-\"\". \\ || ||   |  | \n", -1, -1, poliwag);
        printcFrom("             `.        `.`. \\'.      | | | |||.   .,.','/ /'   |  | \n", -1, -1, poliwag);
        printcFrom("               `-.       `. .:\\      | | | ||'`..___.'.','/   j   | \n", -1, -1, poliwag);
        printcFrom("                  `-._     `-._\\      \\'.`.`..`..__....','   ,   / \n", -1, -1, poliwag);
        printcFrom("                      `--......-\\      \\ `.`.`.......-\"'   ,'   / \n", -1, -1, poliwag);
        printcFrom("                                 `.     `. `-..____,.-\" _.'   ,' \n", -1, -1, poliwag);
        printcFrom("                                   >.     '--...___,..-'   _.\" \n", -1, -1, poliwag);
        printcFrom("                                 ,'  `--,__            _,-\"  `-. \n", -1, -1, poliwag);
        printcFrom("                             _.-'      '   `'--------\"' `.      `-. \n", -1, -1, poliwag);
        printcFrom("                           .'        ,'                   \\        `. \n", -1, -1, poliwag);
        printcFrom("                          .        .'                      `.        . \n", -1, -1, poliwag);
        printcFrom("                          |      ,'                          `._     | \n", -1, -1, poliwag);
        printcFrom("                           `----'                               `\"--\" \n\n", -1, -1, poliwag);
    }

    int ponyta = 0xFBB224;
    if(num == 14) {
        printcFrom("                      .' . \n", -1, -1, ponyta);
        printcFrom("                      .| '\\ \n", -1, -1, ponyta);
        printcFrom("              _...___/`'   . \n", -1, -1, ponyta);
        printcFrom("            ,'             | \n", -1, -1, ponyta);
        printcFrom("        ,|,\"             )/|                             , . \n", -1, -1, ponyta);
        printcFrom("       / |              / , .                            \\` \\ \n", -1, -1, ponyta);
        printcFrom("      /            ...-'  ',                              .  \\ \n", -1, -1, ponyta);
        printcFrom("     .           ,>      .                                |   | \n", -1, -1, ponyta);
        printcFrom("     |          .'   ___`,                  .'  ,--.._,.-'/  ,' \n", -1, -1, ponyta);
        printcFrom("   ..|          |.-\"', /                  ,' | /       .\"'   '. \n", -1, -1, ponyta);
        printcFrom("   \\ '          |  ,'//                   .'  \"    __,._'    | \n", -1, -1, ponyta);
        printcFrom("    \\ `         /.\"_/'_,                 '.       /         _' \n", -1, -1, ponyta);
        printcFrom("     `.\\     _,'   \\.`  ) ,^.              `     '       ,-\" \n", -1, -1, ponyta);
        printcFrom("       |.  .'  _   | `. '-  `,            , \\     `.    ,- \n", -1, -1, ponyta);
        printcFrom("       | `w  ,\" |  |   \\   .'   _,_ :\"'. / 7 . ,`..'   .' \n", -1, -1, ponyta);
        printcFrom("       '|    `.'  /     \\   `-'\"   `   _:_,.}|  :  _. ,' \n", -1, -1, ponyta);
        printcFrom("        \\       .'       `-.      _,.-\"       `-+-`  ' \n", -1, -1, ponyta);
        printcFrom("        |       |           ``--\"'               `. \n", -1, -1, ponyta);
        printcFrom("        \\   .- .                                   \\ \n", -1, -1, ponyta);
        printcFrom("         `.._,\":                                    \\ \n", -1, -1, ponyta);
        printcFrom("               '                                    `.  '-7 \n", -1, -1, ponyta);
        printcFrom("               \\                                  .'`-\"  : \n", -1, -1, ponyta);
        printcFrom("                \\                        .        `      `-' \n", -1, -1, ponyta);
        printcFrom("               j \\                       `.        `.     | \n", -1, -1, ponyta);
        printcFrom("               |  `.  |      .^,'.       ,.+        :    _' \n", -1, -1, ponyta);
        printcFrom("               |   |`.|      |    \\,  ,-'  :`.       \\  /_., \n", -1, -1, ponyta);
        printcFrom("              /    |  |     /     .,-'.     `.`.      \\   / \n", -1, -1, ponyta);
        printcFrom("             /    .' j     / _._,\"     `      ':`.     . ( \n", -1, -1, ponyta);
        printcFrom("            /    /,-\"|    j  `.         `-.    |  .    |/ \n", -1, -1, ponyta);
        printcFrom("            .   `'   |    |    7           |   |   |   | \n", -1, -1, ponyta);
        printcFrom("             `.   .  |    |  v'            |  .'   |   | \n", -1, -1, ponyta);
        printcFrom("               `.  `.|   j'.'              |  |    |  j \n", -1, -1, ponyta);
        printcFrom("                 \\   |   |                j   |   j   | \n", -1, -1, ponyta);
        printcFrom("                  `.j   /\\                |_,j    |  j \n", -1, -1, ponyta);
        printcFrom("                    /  /`\"              ,\"   |    '  | \n", -1, -1, ponyta);
        printcFrom("                   /  j                 '_,.-'   /.-'| \n", -1, -1, ponyta);
        printcFrom("                  |   |                         /__.-' \n", -1, -1, ponyta);
        printcFrom("                 .'`-.' \n", -1, -1, ponyta);
        printcFrom("                /    | \n", -1, -1, ponyta);
        printcFrom("                `----'  \n\n", -1, -1, ponyta);
    }

    int psyduck = 0xFFD200;
    if(num == 15) {
        printcFrom("                                ,-'   ,\"\", \n", -1, -1, psyduck);
        printcFrom("                               / / ,-'.-' \n", -1, -1, psyduck);
        printcFrom("                     _,..-----+-\".\".-'_,.. \n", -1, -1, psyduck);
        printcFrom("             ,...,.\"'             `--.---' \n", -1, -1, psyduck);
        printcFrom("            /,..,'                     `. \n", -1, -1, psyduck);
        printcFrom("          ,'  .'                         `. \n", -1, -1, psyduck);
        printcFrom("         j   /                             `. \n", -1, -1, psyduck);
        printcFrom("         |  /,----._           ,.----.       . \n", -1, -1, psyduck);
        printcFrom("        ,  j    _   \\        .'  .,   `.     | \n", -1, -1, psyduck);
        printcFrom("      ,'   |        |  ____  |         | .\"--+,^. \n", -1, -1, psyduck);
        printcFrom("     /     |`-....-',-'    `._`--....-' _/      | \n", -1, -1, psyduck);
        printcFrom("    /      |     _,'          `--..__  `        ' \n", -1, -1, psyduck);
        printcFrom("   j       | ,-\"'    `    .'         `. `        `. \n", -1, -1, psyduck);
        printcFrom("   |        .\\                        /  |         \\ \n", -1, -1, psyduck);
        printcFrom("   |         `\\                     ,'   |          \\ \n", -1, -1, psyduck);
        printcFrom("   |          |                    |   ,-|           `. \n", -1, -1, psyduck);
        printcFrom("   .         ,'                    |-\"'  |             \\ \n", -1, -1, psyduck);
        printcFrom("    \\       /                      `.    |              . \n", -1, -1, psyduck);
        printcFrom("     ` /  ,'                        |    `              | \n", -1, -1, psyduck);
        printcFrom("      /  /                          |     \\             | \n", -1, -1, psyduck);
        printcFrom("     /  |                           |      \\           / \n", -1, -1, psyduck);
        printcFrom("    /   |                           |       `.       _, \n", -1, -1, psyduck);
        printcFrom("   .     .                         .'         `.__,.',.----, \n", -1, -1, psyduck);
        printcFrom("   |      `.                     ,'             .-""      / \n", -1, -1, psyduck);
        printcFrom("   |        `._               _.'               |        / \n", -1, -1, psyduck);
        printcFrom("   |           `---.......,--\"                  |      ,' \n", -1, -1, psyduck);
        printcFrom("   '                                            '    ,' \n", -1, -1, psyduck);
        printcFrom("    \\                                          /   ,' \n", -1, -1, psyduck);
        printcFrom("     \\                                        /  ,' \n", -1, -1, psyduck);
        printcFrom("      \\                                      / ,' \n", -1, -1, psyduck);
        printcFrom("       `.                                   ,+' \n", -1, -1, psyduck);
        printcFrom("         >.                               ,' \n", -1, -1, psyduck);
        printcFrom("     _.-'  `-.._                      _,-'-._ \n", -1, -1, psyduck);
        printcFrom("   ,__          `\",-............,.---\"       `. \n", -1, -1, psyduck);
        printcFrom("      \\..---. _,-'            ,'               `. \n", -1, -1, psyduck);
        printcFrom("             \"                '..,--.___,-\"\"\"---' \n\n", -1, -1, psyduck);
    }

    int rattata = 0xB91E83;
    if(num == 16) {
        printcFrom("                                         ,'""`--. \n", -1, -1, rattata);
        printcFrom("                                        |     __ `-. \n", -1, -1, rattata);
        printcFrom("                                        |    /  `.  `. \n", -1, -1, rattata);
        printcFrom("                                         \\        ,   `. \n", -1, -1, rattata);
        printcFrom("                                          `.      \\_    `. \n", -1, -1, rattata);
        printcFrom("                                            `.    | `.    \\ \n", -1, -1, rattata);
        printcFrom("                                              `--\"    `.   ` \n", -1, -1, rattata);
        printcFrom("                                                        `.  ` \n", -1, -1, rattata);
        printcFrom("                    ,.._                                  \\  ` \n", -1, -1, rattata);
        printcFrom("                  /_,.  `.                                 \\  ` \n", -1, -1, rattata);
        printcFrom("                 j/   .   \\                  ___            \\  \\ \n", -1, -1, rattata);
        printcFrom("                 |    |   `____         _,--'   `.           .  L \n", -1, -1, rattata);
        printcFrom("                  L  /`--\"'    `'--._ ,'   ,-`'\\ |            . | \n", -1, -1, rattata);
        printcFrom("                   |-                /  ,''     ||            | | \n", -1, -1, rattata);
        printcFrom("        -v._      /                   ,'        ||            | | \n", -1, -1, rattata);
        printcFrom("          `.`-._,'               _     \\        |j    _,...   | | \n", -1, -1, rattata);
        printcFrom("            `,.'             _,-. \\     |      /,---""     `- | | \n", -1, -1, rattata);
        printcFrom("           .'              ,\".   ||     `..___/,'            `' | \n", -1, -1, rattata);
        printcFrom("           |   ,         _/`-'  /,'                            `| \n", -1, -1, rattata);
        printcFrom("           |-.__.-'\"''\"\"' \"\"\"\"\"\"\"\"--`_,...-----''''--...--      `. \n", -1, -1, rattata);
        printcFrom("            `.____,..              ""   __,..---\"\"\"              | \n", -1, -1, rattata);
        printcFrom("             |       `              --\"'.                        ` \n", -1, -1, rattata);
        printcFrom("             |     ,' `._                \'                       ` \n", -1, -1, rattata);
        printcFrom("             | |  .^.    `.             /                          `. \n", -1, -1, rattata);
        printcFrom("            ,'_]__|  \\   / `.          /          /____._            `._ \n", -1, -1, rattata);
        printcFrom("          ,'          \\ j    '        /          /       `.             `. \n", -1, -1, rattata);
        printcFrom("    ___,.' `._       __L/    |     __'          /     _, / \\             | \n", -1, -1, rattata);
        printcFrom("   `-._       L,.-\"\"\"  .    ,' _.-','          /-----'-./   `--.         | \n", -1, -1, rattata);
        printcFrom("      '   / ,'         '..'\"_,'    /         F /  .\"'_,'        |.__     ' \n", -1, -1, rattata);
        printcFrom("      / ,.\\,'              ""      /         / (,'\\ .'        ,.-\"'  `.  j \n", -1, -1, rattata);
        printcFrom("      -'   '                      /        ,'     `\"         / __/' .- ,' \n", -1, -1, rattata);
        printcFrom("                               __.'\"`.    /                 `-' | _,L,' \n", -1, -1, rattata);
        printcFrom("                             .',      `\"\"'                      '/,-- \n", -1, -1, rattata);
        printcFrom("                               / _..' _,,' \n", -1, -1, rattata);
        printcFrom("                              ,' `-\"' \n\n", -1, -1, rattata);
    }

    int ditto = 0xE0B7CE;
    if(num == 17) {
        printcFrom("                                         ,--._ \n", -1, -1, ditto);
        printcFrom("                                      _,'     `. \n", -1, -1, ditto);
        printcFrom("                            ,.-------\"          `. \n", -1, -1, ditto);
        printcFrom("                           /                 \"    `-.__ \n", -1, -1, ditto);
        printcFrom("                           .         \"        _,        `._ \n", -1, -1, ditto);
        printcFrom("                           |            __..-\"             `. \n", -1, -1, ditto);
        printcFrom("                           |        ''\"'                     `._ \n", -1, -1, ditto);
        printcFrom("                           |                                    `\"-. \n", -1, -1, ditto);
        printcFrom("                           '                                        `. \n", -1, -1, ditto);
        printcFrom("                          .                                          | \n", -1, -1, ditto);
        printcFrom("                         /                                           | \n", -1, -1, ditto);
        printcFrom("                      _,'                                           ,' \n", -1, -1, ditto);
        printcFrom("                    ,\"                                             / \n", -1, -1, ditto);
        printcFrom("                   .                                              / \n", -1, -1, ditto);
        printcFrom("                   |                                             / \n", -1, -1, ditto);
        printcFrom("                   |                                            . \n", -1, -1, ditto);
        printcFrom("                   '                                            | \n", -1, -1, ditto);
        printcFrom("                    `.                                          | \n", -1, -1, ditto);
        printcFrom("                      `.                                        | \n", -1, -1, ditto);
        printcFrom("                        `.                                      ' \n", -1, -1, ditto);
        printcFrom("                          .                                      . \n", -1, -1, ditto);
        printcFrom("                          |                                       `. \n", -1, -1, ditto);
        printcFrom("                          '                                        | \n", -1, -1, ditto);
        printcFrom("                        ,'                                         | \n", -1, -1, ditto);
        printcFrom("                      ,'                                           ' \n", -1, -1, ditto);
        printcFrom("                     /                                _...._      / \n", -1, -1, ditto);
        printcFrom("                     .                              ,-'      `\"'--' \n", -1, -1, ditto);
        printcFrom("      ___            |                            ,' \n", -1, -1, ditto);
        printcFrom("   ,-'   `\"-._     _.'                          ,' \n", -1, -1, ditto);
        printcFrom("  /           `\"--'             _,....__     _,' \n", -1, -1, ditto);
        printcFrom(" '                            .'        `---' \n", -1, -1, ditto);
        printcFrom(" `                 ____     ,' \n", -1, -1, ditto);
        printcFrom("  .           _.-'\"    `---' \n", -1, -1, ditto);
        printcFrom("   `-._    _.\" \n", -1, -1, ditto);
        printcFrom("       \"\"\"' \n\n", -1, -1, ditto);
    }

    int squirtle = 0x00FFFF;
    if(num == 18){
        printcFrom("                  _,........__ \n", -1, -1, squirtle);
        printcFrom("               ,-'            \"`-. \n", -1, -1, squirtle);
        printcFrom("             ,'                   `-. \n", -1, -1, squirtle);
        printcFrom("           ,'                        \\ \n", -1, -1, squirtle);
        printcFrom("         ,'                           . \n", -1, -1, squirtle);
        printcFrom("         .'\\               ,"".       ` \n", -1, -1, squirtle);
        printcFrom("        ._.'|             / |  `       \\ \n", -1, -1, squirtle);
        printcFrom("        |   |            `-.'  ||       `. \n", -1, -1, squirtle);
        printcFrom("        |   |            '-._,'||       | \\ \n", -1, -1, squirtle);
        printcFrom("        .`.,'             `..,'.'       , |`-. \n", -1, -1, squirtle);
        printcFrom("        l                       .'`.  _/  |   `. \n", -1, -1, squirtle);
        printcFrom("        `-.._'-   ,          _ _'   -\" \\  .     ` \n", -1, -1, squirtle);
        printcFrom("   `.\"\"\"\"\"'-.`-...,---------','         `. `....__. \n", -1, -1, squirtle);
        printcFrom("   .'        `\"-..___      __,'\\          \\  \\     \\ \n", -1, -1, squirtle);
        printcFrom("   \\_ .          |   `\"\"\"\"'    `.           . \\     \\ \n", -1, -1, squirtle);
        printcFrom("     `.          |              `.          |  .     L \n", -1, -1, squirtle);
        printcFrom("       `.        |`--...________.'.        j   |     | \n", -1, -1, squirtle);
        printcFrom("         `._    .'      |          `.     .|   ,     | \n", -1, -1, squirtle);
        printcFrom("            `--,\\       .            `7""' |  ,      | \n", -1, -1, squirtle);
        printcFrom("               ` `      `            /     |  |      |    _,-'\"\"\"`-. \n", -1, -1, squirtle);
        printcFrom("                \\ `.     .          /      |  '      |  ,'          `. \n", -1, -1, squirtle);
        printcFrom("                 \\  v.__  .        '       .   \\    /| /              \\ \n", -1, -1, squirtle);
        printcFrom("                  \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                | \n", -1, -1, squirtle);
        printcFrom("                   `        .        `._ ___,j.  `/ .-       ,---.     | \n", -1, -1, squirtle);
        printcFrom("                   ,`-.      \\         .\"     `.  |/        j     `    | \n", -1, -1, squirtle);
        printcFrom("                  /    `.     \\       /         \\ /         |     /    j \n", -1, -1, squirtle);
        printcFrom("                 |       `-.   7-.._ .          |\"          '         / \n", -1, -1, squirtle);
        printcFrom("                 |          `./_    `|          |            .     _,' \n", -1, -1, squirtle);
        printcFrom("                 `.           / `----|          |-............`---' \n", -1, -1, squirtle);
        printcFrom("                   \\          \\      |          | \n", -1, -1, squirtle);
        printcFrom("                  ,'           )     `.         | \n", -1, -1, squirtle);
        printcFrom("                   7____,,..--'      /          | \n", -1, -1, squirtle);
        printcFrom("                                     `---.__,--.' \n\n", -1, -1, squirtle);
    }

    int horsea = 0x51D1F6;
    if(num == 19) {
        printcFrom("                                _,..----.._ \n", -1, -1, horsea);
        printcFrom("       ,\"''-.               _.-'           `\"-._ \n", -1, -1, horsea);
        printcFrom("      .,-.   `._          ,'    ,---.           `.             _,.. \n", -1, -1, horsea);
        printcFrom("      ||  \\     `._     ,'    .' |   .            `.     _,.-\"' _,' \n", -1, -1, horsea);
        printcFrom("      ||   .       `-._.      |.'|   |            _...-\"'    _,' \n", -1, -1, horsea);
        printcFrom("      ''   |           '      |  '   |         --'       _,-' \n", -1, -1, horsea);
        printcFrom("       \\  |                  '.'    |                 ,' \n", -1, -1, horsea);
        printcFrom("        .`.'                   `.    '                ( \n", -1, -1, horsea);
        printcFrom("         `.____                  `--'                  `--..__ \n", -1, -1, horsea);
        printcFrom("               ``\"-.._                                        ``--..__ \n", -1, -1, horsea);
        printcFrom("                      |\"                                              ``. \n", -1, -1, horsea);
        printcFrom("                      `                             .--\"''\"\"\"'`--------' \n", -1, -1, horsea);
        printcFrom("                       `.                           \\ \n", -1, -1, horsea);
        printcFrom("           ,-\"'`-._      `-._                 `._    `. \n", -1, -1, horsea);
        printcFrom("          /        `.     ,._`-.._          _,'  `-.   . \n", -1, -1, horsea);
        printcFrom("         .    _      `.   |  `\"-._`     .-\"'        `-. `. \n", -1, -1, horsea);
        printcFrom("         |     `\"-._   `. |--.._  `._   \\              `. . \n", -1, -1, horsea);
        printcFrom("         |          `-._ `|     `-._ `-. `.              `' \n", -1, -1, horsea);
        printcFrom("         `        ._    `/'         `-. `. . \n", -1, -1, horsea);
        printcFrom("          \\         `\"-.'  .-....__    `. `.`. \n", -1, -1, horsea);
        printcFrom("           .          /    '       `\"-.._   | \\ \n", -1, -1, horsea);
        printcFrom("            `.       /------\\            `  |  \\ \n", -1, -1, horsea);
        printcFrom("              `.___./        `              '   . \n", -1, -1, horsea);
        printcFrom("                   ,          `._        ,-'    | \n", -1, -1, horsea);
        printcFrom("                   |.-\"''\"\"'--.._`\"---'\"/       | \n", -1, -1, horsea);
        printcFrom("                   |  ______      `\"-../        | \n", -1, -1, horsea);
        printcFrom("                   .\"'      `\".       /         ' \n", -1, -1, horsea);
        printcFrom("                 ,'            .     /         . \n", -1, -1, horsea);
        printcFrom("                .              |   .'         / \n", -1, -1, horsea);
        printcFrom("                |       ,'     |.-'          / \n", -1, -1, horsea);
        printcFrom("                |       |      '            ' \n", -1, -1, horsea);
        printcFrom("                 .       `-..-\"          _,' \n", -1, -1, horsea);
        printcFrom("                  `.                  _,\" \n", -1, -1, horsea);
        printcFrom("                    `._          __.-' \n", -1, -1, horsea);
        printcFrom("                       `'------\"' \n\n", -1, -1, horsea);
    }
}
